ARG BASEOS
FROM nix_${BASEOS}_base:f54e2e28ba1013d1cedf4d814276e0b3175c0520

USER root
ARG ADDUSER

COPY Docker/config.nix $HOME/.config/nixpkgs/
COPY Docker/dev-env.nix $ENVSDIR/
COPY Docker/persist-env.sh $ENVSDIR/
RUN chown -R $nixuser:$nixuser $ENVSDIR

#
# Initialize environment a bit for faster container spinup/use later
#
USER $nixuser
RUN $nixenv && cd /tmp && sh $ENVSDIR/persist-env.sh $ENVSDIR/dev-env.nix
#

USER root

#
# The below method isn't ideal, as it could break - better to copy in an sshd_config file
# or somehow use nix to configure sshd
# sed -i 's/.*PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
#
# alternatively ...:
# TODO: write a script to check if PermitRootLogin is already set, and replace it if so, else add it
#
ENV SSHD_PATH ""
RUN SSHD_PATH=$(su -c "$nixenv && nix-build '<nixpkgs>' --no-build-output --no-out-link -A openssh" "${nixuser:?}") && \
  mkdir -p /etc/ssh && cp "$SSHD_PATH/etc/ssh/sshd_config" /etc/ssh/sshd_config && \
  mkdir /var/run/sshd && \
  printf "PermitRootLogin yes\n" >> /etc/ssh/sshd_config && \
  id -u sshd || ${ADDUSER} sshd && \
  mkdir -p /var/empty/sshd/etc && \
  cd /var/empty/sshd/etc && \
  ln -s /etc/localtime localtime
  
USER $nixuser


# ------------------------------------------------------------
# Set-Up SSH with our Github deploy key
# ------------------------------------------------------------

ENV SSHDIR ${HOME}/.ssh/

RUN mkdir -p ${SSHDIR}

ADD Docker/ssh/config ${SSHDIR}/config
ADD Docker/ssh/id_rsa.mpi ${SSHDIR}/id_rsa
ADD Docker/ssh/id_rsa.mpi.pub ${SSHDIR}/id_rsa.pub
ADD Docker/ssh/id_rsa.mpi.pub ${SSHDIR}/authorized_keys

USER root

RUN chmod -R 600 ${SSHDIR}* && \
    chown -R ${nixuser}:${nixuser} ${SSHDIR}

# ------------------------------------------------------------
# Configure OpenMPI
# ------------------------------------------------------------

RUN rm -fr ${HOME}/.openmpi && mkdir -p ${HOME}/.openmpi
ADD Docker/default-mca-params.conf ${HOME}/.openmpi/mca-params.conf
RUN chown -R ${nixuser}:${nixuser} ${HOME}/.openmpi

# ------------------------------------------------------------
# Copy Lake_Problem_DPS code
# ------------------------------------------------------------

COPY DataInPaper ${HOME}/Lake_Problem_DPS/DataInPaper
COPY FigureGeneration ${HOME}/Lake_Problem_DPS/FigureGeneration
COPY Optimization ${HOME}/Lake_Problem_DPS/Optimization
COPY Re-evaluation ${HOME}/Lake_Problem_DPS/Re-evaluation

COPY compile.sh ${HOME}/Lake_Problem_DPS

COPY Optimization/moeaframework.h ${HOME}/Lake_Problem_DPS/Optimization/borg
COPY Optimization/moeaframework.c ${HOME}/Lake_Problem_DPS/Optimization/borg

RUN chown -R ${nixuser}:${nixuser} ${HOME}/Lake_Problem_DPS/DataInPaper
RUN chown -R ${nixuser}:${nixuser} ${HOME}/Lake_Problem_DPS/FigureGeneration
RUN chown -R ${nixuser}:${nixuser} ${HOME}/Lake_Problem_DPS/Optimization
RUN chown -R ${nixuser}:${nixuser} ${HOME}/Lake_Problem_DPS/Re-evaluation


# TODO: remove borg before making public.  Temporary for testing.

USER $nixuser
COPY Docker/default.nix $ENVSDIR/
RUN $nixenv && cd /tmp && nix-shell $ENVSDIR/default.nix --run ${HOME}/Lake_Problem_DPS/compile.sh
USER root

RUN passwd -d $nixuser

# ------------------------------------------------------------
# Copy MPI4PY example scripts
# ------------------------------------------------------------

ENV TRIGGER 1

ADD Docker/mpi4py_benchmarks ${HOME}/mpi4py_benchmarks
RUN chown -R ${nixuser}:${nixuser} ${HOME}/mpi4py_benchmarks

#Copy this last to prevent rebuilds when changes occur in them:
COPY Docker/entrypoint* $ENVSDIR/
#COPY Docker/default.nix $ENVSDIR/

RUN chown $nixuser:$nixuser $ENVSDIR/entrypoint
ENV PATH="${PATH}:/usr/local/bin"

EXPOSE 22
ENTRYPOINT ["/bin/sh", "./entrypoint"]
